routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('lang/{locale}', 'HomeController@lang');

Route::get('/shop','Frontend\ShopController@index');



Route::get('/product-detail/{id}','Frontend\ShopController@productDetail');

Route::resource('/product','Admin\ProductController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'image', 'description',
    ];

     /**
     * Get category with product
     */
    public function categories()
    {
        return $this->hasMany(Category::class);
    }
    /**
     * Get brands with product
     */
    public function brands()
    {
        return $this->hasMany(Brand::class);
    }
    /**
     * Get colors with product
     */
    public function colors()
    {
        return $this->hasMany(ProductColor::class);
    }
     /**
     * Get prices with product
     */
    public function prices()
    {
        return $this->hasMany(ProductPrice::class);
    }
    /**
     * Get size with product
     */
    public function sizes()
    {
        return $this->hasMany(ProductSize::class);
    }
}

app/ProductTYpe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductTYpe extends Model
{
    //
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Traits\ImageTrait;
use App\Product;
use App\Brand;
use App\Category;
use App\ProductColor;
use App\ProductPrice;
use App\ProductSize;

class ProductController extends Controller
{
    use ImageTrait;
    protected $image = 'image';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('admin.products.product',compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $input['image'] = $this->imagePhoto($request);
       $products = Product::create($input);
       if ($products) {
           Brand::create(['product_id'=>$products->id,'brand'=>$request->brand]);
           Category::create(['product_id'=>$products->id,'category'=>$request->category]);
           ProductPrice::create([
               'product_id'=>$products->id,
               'sell_price'=>$request->sell_price,
               'purchase_price'=>$request->purchase_price]);
            ProductSize::create(['product_id'=>$products->id,'size'=>$request->size]);
            ProductColor::create(['product_id'=>$products->id,'color'=>$request->color]);
           return redirect('/home')->with('success','record created successfully.'); 
          
       } else {
           return false;
       }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $products = Product::where('id',$id)->with('brands','categories','colors','prices','sizes')->first();
        // return view('admin.products.read',compact('products'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $products = Product::with('brands','categories','colors','prices','sizes')->first();
        return view('admin.products.edit',compact('products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $input['image'] = $this->imagePhoto($request);
        $products = Product::where('id',$id)->update($input);
       if ($products) {
           Brand::create(['product_id'=>$id,'brand'=>$request->brand]);
           Category::create(['product_id'=>$id,'category'=>$request->category]);
           ProductPrice::create([
               'product_id'=>$id,
               'sell_price'=>$request->sell_price,
               'purchase_price'=>$request->purchase_price]);
            ProductSize::create(['product_id'=>$id,'size'=>$request->size]);
            ProductColor::create(['product_id'=>$id,'color'=>$request->color]);
           return redirect('/product')->with('message','record created successfully.'); 
          
       } else {
        return redirect('/product')->with('error','something wrong.'); 
       }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <div class="row">
       <div class="col-md-12">
           <div class="card">
               <div class="card-header">Create Product Form</div>
               <div class="card-body"> 
                    <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                     {{csrf_field()}}
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" name="name"  placeholder="Enter name" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Image</label>
                            <input type="file" name="image"  class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            <input type="text" name="description"  placeholder="Enter description" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            <input type="text" name="category"  placeholder="Enter category" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Brand</label>
                            <input type="text" name="brand"  placeholder="Enter brand" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Sell Price</label>
                            <input type="text" name="sell_price"  placeholder="Enter sellprice" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Purchase Price</label>
                            <input type="text" name="purchase_price"  placeholder="Enter purchaseprice" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Product Color</label>
                              <select name="color" id="" class="form-control">
                                <option value="">--choose color--</option>
                                <option value="black">black</option>
                                <option value="yellow">yellow</option>
                                <option value="green">green</option>
                                <option value="pink">pink</option>
                                <option value="red">red</option>
                                <option value="blue">blue</option>
                                <option value="gray">gray</option>
                              </select>
                        </div>
                        <div class="form-group">
                            <label for="">Product Size</label>
                              <select name="size" id="" class="form-control">
                                <option value="">--choose size--</option>
                                <option value="xsamll">xsmall</option>
                                <option value="small">small</option>
                                <option value="medium">medium</option>
                                <option value="large">large</option>
                                <option value="xlarage">xlarage</option>
                              </select>
                        </div>
                        <button class="btn btn-info bg-md" type="submit">Create Product</button>
                    </form>
               </div>
           </div>
       </div>
    </div>
</div>
@endsection

resources/views/admin/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <div class="row">
       <div class="col-md-12">
           <div class="card">
               <div class="card-header">Edit Product Form</div>
               <div class="card-body"> 
                    <form action="{{route('product.update',$products->id)}}" method="POST" enctype="multipart/form-data">
                     {{csrf_field()}}
                        <div class="form-group">
                            <label for="">Name</label>
                            <input type="text" name="name"  placeholder="Enter name" class="form-control" value="{{$products->name}}">
                        </div>
                        <div class="form-group">
                            <label for="">Image</label>
                            <input type="file" name="image"  class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="">Description</label>
                            <input type="text" name="description"  placeholder="Enter description" class="form-control"  value="{{$products->description}}">
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            <input type="text" name="category"  placeholder="Enter category" class="form-control"  value="{{$products->categories[0]->category}}">
                        </div>
                        <div class="form-group">
                            <label for="">Brand</label>
                            <input type="text" name="brand"  placeholder="Enter brand" class="form-control"  value="{{$products->brands[0]->brand}}">
                        </div>
                        <div class="form-group">
                            <label for="">Sell Price</label>
                            <input type="text" name="sell_price"  placeholder="Enter sellprice" class="form-control" value="{{$products->prices[0]->sell_price}}">
                        </div>
                        <div class="form-group">
                            <label for="">Purchase Price</label>
                            <input type="text" name="purchase_price"  placeholder="Enter purchaseprice" class="form-control" value="{{$products->prices[0]->porchase_price}}">
                        </div>
                        <div class="form-group">
                            <label for="">Product Color</label>
                              <select name="color" id="" class="form-control">
                                <option value="">--choose color--</option>
                                <option value="black">black</option>
                                <option value="yellow">yellow</option>
                                <option value="green">green</option>
                                <option value="pink">pink</option>
                                <option value="red">red</option>
                                <option value="blue">blue</option>
                                <option value="gray">gray</option>
                              </select>
                        </div>
                        <div class="form-group">
                            <label for="">Product Size</label>
                              <select name="size" id="" class="form-control">
                                <option value="">--choose size--</option>
                                <option value="xsamll">xsmall</option>
                                <option value="small">small</option>
                                <option value="medium">medium</option>
                                <option value="large">large</option>
                                <option value="xlarage">xlarage</option>
                              </select>
                        </div>
                        <button class="btn btn-info bg-md" type="submit">Create Product</button>
                    </form>
               </div>
           </div>
       </div>
    </div>
</div>
@endsection

resources/views/admin/products/product.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <div class="row">
       <div class="col-md-12">
           <a href="{{route('product.create')}}"><button class="btn  btn-success btn-md pull-right">Add Product</button></a>
            @if(session()->has('message'))
              <div class="alert alert-success">
               {{session()->get('message')}}
              </div>
            @endif
           <div class="card">
              <div class="card-header">Products</div>
              <div class="card-body"> 
                <table class="table">
                   <thead>
                     <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Image</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                   </thead>
                   @foreach ( $products as $product)
                   <tbody>
                      <tr>
                         <td>{{$product->id}}</td>
                         <td>{{$product->name}}</td>
                         <td><img src="{{$product->image}}" alt="" height="50" width="50"></td>
                         <td>{{$product->description}}</td>
                         <td>
                            <a href="{{route('product.show',$product->id)}}"><button class="btn btn-info btn-sm">More</button></a>
                            <a href="{{route('product.edit',$product->id )}}"><button class="btn btn-success btn-sm">Edit</button></a>
                            <a href=""><button class="btn btn-danger btn-sm">Dell</button></a>
                        </td>
                      </tr>
                   </tbody>
                   @endforeach
                </table>
              </div>
           </div>
       </div>
       
   </div>
</div>

@endsection

resources/views/admin/products/read.blade.php
@extends('layouts.master')

@section('title','Product')

@section('content')
<div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						
						<div class="preview-pic tab-content">
						  <div class="tab-pane active" id="pic-1"><img src="{{$products->image}}" /></div>
						</div>
						<ul class="preview-thumbnail nav nav-tabs">
						  <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="{{$products->image}}" /></a></li>
						  <li><a data-target="#pic-2" data-toggle="tab"><img src="{{$products->image}}" /></a></li>
						  <li><a data-target="#pic-3" data-toggle="tab"><img src="{{$products->image}}" /></a></li>
						  <li><a data-target="#pic-4" data-toggle="tab"><img src="{{$products->image}}" /></a></li>
						  <li><a data-target="#pic-5" data-toggle="tab"><img src="{{$products->image}}" /></a></li>
						</ul>
						
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{$products->name}}</h3>
						<div class="rating">
							<div class="stars">
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star"></span>
								<span class="fa fa-star"></span>
							</div>
							<span class="review-no">41 reviews</span>
						</div>
						<p class="product-description">{{$products->description}}</p>
						<h4 class="price">current price: <span>Rs = {{$products->prices[0]->sell_price}}</span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
					
						<h5 class="colors">Available Colors:
							<span class="color" style="background-color:{{$products->colors[0]->color}};"></span>
						</h5>
						<div class="action">
							<button class="add-to-cart btn btn-default" type="button">add to cart</button>
							<button class="like btn btn-default" type="button"><span class="fa fa-heart"></span></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

@endsection